### PR TITLE
fix: company name in webconsole and other files

### PR DESCRIPTION
**Pull request by arriqaaq**
change company name from CodeNotary, Inc to Codenotary, Inc

References #1308

### CODE REVIEW

**Comment by arriqaaq** [comment]
cc: @moshix

**Comment by tomekkolo** [comment]
there should be no comma after Codenotary. So the change should be "Codenotary Inc"

**Comment by arriqaaq** [comment]
@tomekkolo done

**Review by jeroiraz — APPROVED** [review]
CI workflow is failing at `TestConn_BeginTx`, while it's not related to these changes please ensure it succeed before merging into master

**Review by jeroiraz — DISMISSED** [review]

**Review by tomekkolo — APPROVED** [review]

**Pull request merged**
