### PR TITLE
Add CORS middleware to /metrics and /debug/vars HTTP endpoints

### PR DESCRIPTION
**Pull request by padurean**
I've created this PR towards the branch _fix/metrics-cors_ other one (for multi-database metrics).
Once we merge that one, i will change the target branch to `master`.

### CODE REVIEW

**Comment by dmacvicar** [comment]
@Hextar I think your review would be the most useful here, checking if you can access the metrics from the front-end. Note: please test with the console fully embedded and not with the development proxy.

**Comment by padurean** [comment]
@dmacvicar @Hextar I've already closed this PR and deleted the branch: please use the branch from this PR (which contains both the multi-db metrics and the CORS): https://github.com/codenotary/immudb/pull/756

**Comment by Hextar** [comment]
@padurean Checking with curl I see the following headers, so everything should work fine.

I still need to integrate in with the FE as apparently axios still need some configuration to be set.

```
Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, DELETE
Access-Control-Allow-Origin: *
```

**Comment by Hextar** [comment]
@padurean but more precisely I'm receiving the following response

```
Access to XMLHttpRequest at 'http://localhost:9497/metrics' from origin 'http://localhost:8081' has been blocked by CORS policy: Request header field access-control-allow-methods is not allowed by Access-Control-Allow-Headers in preflight response.
```

I think one thing is still missing from the Server, as **Access-Control-Allow-Methods** and **Access-Control-Allow-Origin** aren't added to the **Access-Control-Allow-Headers** header.

**Comment by padurean** [comment]
These are the headers that are added both for OPTIONS and any other method:
```go
w.Header().Set("Access-Control-Allow-Origin", "*")
 w.Header().Set("Access-Control-Allow-Methods", "POST, GET, OPTIONS, PUT, DELETE")
 w.Header().Set("Access-Control-Allow-Headers", "Accept, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization")
```

Also, this PR is closed and the branch is deleted. Please test with the branch in the other PR that i mentioned in my previous comment.

**Pull request closed without merging**
