### PR TITLE
chore(embedded/sql): support for escaped strings

### PR DESCRIPTION
**Pull request by jeroiraz**
The PR was modified to provide sql standard escaping with single quotes

```sql
create table mytable(title varchar[50], primary key title)
insert into mytable(title) values ('my escaped ''string''')

select * from mytable

+---------------------------+
| (DEFAULTDB MYTABLE TITLE) |
+---------------------------+
| "my escaped 'string'"     |
+---------------------------+
```

While we can support both escaping methods, the previous one was not correctly covering all the cases.

Signed-off-by: Jeronimo Irazabal <jeronimo.irazabal@gmail.com>

### CODE REVIEW

**Comment by byo** [comment]
I think the standard way to escape single quotes in SQL is by doubling them (https://www.databasestar.com/sql-escape-single-quote/), it's not a standard notation in SQL to use `\` escaping character. I guess many standard tools will follow that convention (maybe even golang stdlib).

**Comment by SimoneLazzaris** [comment]
I think that as there is at least _one_ way to insert special characters (like the quote in my case) we're safe. The backslash is quite accepted as an escape char, so I think that it is reasonable.

**Review by SimoneLazzaris — DISMISSED** [review]
LGTM

**Review by SimoneLazzaris — APPROVED** [review]
Tested, it works

**Review by byo — APPROVED** [review]
:+1:

**Pull request merged**
