### PR TITLE
Correcting grammar in README.md

### PR DESCRIPTION
**Pull request by davidsbond**
Hello, I saw you post your project on Reddit.

While taking a read of your README, I noticed some grammatical mistakes and have raised this PR to address them.

Seems like an interesting project and I wish you all the best!

### CODE REVIEW

**Comment by mmeloni** [comment]
@davidsbond Thank you very much for your contribute. We are working hard on docs and we don't have merged in time your PR in order to avoid conflicts. Could you please fix them and push again?

**Comment by davidsbond** [comment]
Hey @mmeloni, no problem

**Comment by davidsbond** [comment]
Hi @mmeloni I've reapplied my changes after fixing conflicts. Picked up a couple additional typos.

**Comment by mmeloni** [comment]
@davidsbond thanks very much!

**Pull request merged**
